limit_req_zone $binary_remote_addr zone=api:10m rate=30r/m;



server {
    listen 80;

    server_name localhost;

    location / {
        limit_req zone=api  nodelay;
        proxy_pass http://127.0.0.1:8000;
        limit_req_status 429;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    

    
    error_page 429 503 = /rate_limit_exceeded;
    if ($http_user_agent ~* (nmap|nikto|wikto|sf|sqlmap|bsqlbf|w3af|acunetix|havij|appscan)) {
        
        return 403 '{"error": "user agent is not supported"}';
    }

    location = /rate_limit_exceeded {
        internal;
        default_type application/json;
        return 429 '{"error": "Too many requests, please slow down"}';
    }

    location ~ /\.(git|env|htaccess|htpasswd) {
        deny all;
        return 404;
    }
}